"""Read query results back into pandas, and reproduce the JOIN without SQL.

Two things are demonstrated here:

1. pd.read_sql(...) reading three of run_queries.py's queries back into
   DataFrames (the brief asks for at least two).
2. The Q6 join reproduced with pd.merge(...) on in-memory DataFrames -- the two
   tables are loaded with plain "SELECT * FROM <table>" and every join, filter,
   sort and limit step is then done by pandas, with no SQL JOIN involved.

The two versions of the join are printed side by side and compared with
pd.testing.assert_frame_equal, which raises if they differ in any cell or dtype.
"""

import sqlite3

import pandas as pd

from run_queries import JOIN_QUERY, QUERIES_BY_NAME

DB_PATH = "books.db"
OUTPUT_MD = "pandas_check_output.md"

QUERY_MOST_EXPENSIVE = QUERIES_BY_NAME["Q2 - ORDER BY + LIMIT"]
QUERY_MID_PRICED = QUERIES_BY_NAME["Q4 - BETWEEN"]


def join_with_pandas(books, categories):
    """Reproduce JOIN_QUERY using only pandas operations."""
    merged = pd.merge(books, categories, on="category_id", how="inner")

    return (
        merged[merged["rating"] >= 4]
        .sort_values(
            by=["category_name", "rating", "title"],
            ascending=[True, False, True],
            kind="mergesort",  # stable, so ties resolve the same way SQLite does
        )
        .head(10)[["title", "category_name", "rating", "price_gbp", "price_inr"]]
        .reset_index(drop=True)
    )


def main():
    connection = sqlite3.connect(DB_PATH)
    report = ["# pandas read-back and merge equivalence\n",
              "Generated by `pandas_check.py`.\n"]

    # --- Part 1: read query results back with pd.read_sql -------------------
    print("=" * 78)
    print("PART 1 - reading SQL query results back with pd.read_sql")
    print("=" * 78)

    expensive = pd.read_sql(QUERY_MOST_EXPENSIVE, connection)
    mid_priced = pd.read_sql(QUERY_MID_PRICED, connection)

    print(f"\n[A] 10 most expensive books  ->  shape {expensive.shape}")
    print(expensive.to_string(index=False))
    print(f"\n[B] Books priced GBP 20-30  ->  shape {mid_priced.shape}")
    print(mid_priced.head(10).to_string(index=False))
    print(f"    ... {len(mid_priced)} rows total")

    report.append("## Part 1 - pd.read_sql read-back\n")
    report.append(f"**[A] 10 most expensive books** (shape {expensive.shape})\n")
    report.append(expensive.to_markdown(index=False) + "\n")
    report.append(f"**[B] Books priced GBP 20-30** (shape {mid_priced.shape}, first 10 shown)\n")
    report.append(mid_priced.head(10).to_markdown(index=False) + "\n")

    # --- Part 2: the join, both ways ---------------------------------------
    print("\n" + "=" * 78)
    print("PART 2 - the same JOIN computed two ways")
    print("=" * 78)

    via_sql = pd.read_sql(JOIN_QUERY, connection)

    # Load the two tables whole; the join itself is done by pandas below.
    books = pd.read_sql("SELECT * FROM books", connection)
    categories = pd.read_sql("SELECT * FROM categories", connection)
    via_merge = join_with_pandas(books, categories)

    print(f"\n[SQL]    pd.read_sql(JOIN_QUERY)   -> shape {via_sql.shape}")
    print(via_sql.to_string(index=False))
    print(f"\n[pandas] pd.merge(books, categories) -> shape {via_merge.shape}")
    print(via_merge.to_string(index=False))

    # --- Part 3: explicit side-by-side comparison --------------------------
    comparison = pd.DataFrame(
        {
            "sql_title": via_sql["title"].str.slice(0, 34),
            "merge_title": via_merge["title"].str.slice(0, 34),
            "sql_rating": via_sql["rating"],
            "merge_rating": via_merge["rating"],
            "sql_price_inr": via_sql["price_inr"],
            "merge_price_inr": via_merge["price_inr"],
        }
    )
    comparison["match"] = via_sql.eq(via_merge).all(axis=1)

    print("\n" + "-" * 78)
    print("Side-by-side comparison (titles truncated to 34 chars for display)")
    print("-" * 78)
    print(comparison.to_string(index=False))

    pd.testing.assert_frame_equal(via_sql, via_merge)
    verdict = f"IDENTICAL - all {len(via_sql)} rows and dtypes match"
    print(f"\nassert_frame_equal passed: {verdict}")

    report.append("## Part 2 - JOIN via SQL vs JOIN via pd.merge\n")
    report.append(f"**Via `pd.read_sql(JOIN_QUERY)`** (shape {via_sql.shape})\n")
    report.append(via_sql.to_markdown(index=False) + "\n")
    report.append(f"**Via `pd.merge(books, categories)`, no SQL join** (shape {via_merge.shape})\n")
    report.append(via_merge.to_markdown(index=False) + "\n")
    report.append("## Part 3 - side-by-side comparison\n")
    report.append(comparison.to_markdown(index=False) + "\n")
    report.append(f"`pd.testing.assert_frame_equal` passed: **{verdict}**\n")

    connection.close()

    with open(OUTPUT_MD, "w", encoding="utf-8") as handle:
        handle.write("\n".join(report))
    print(f"Wrote comparison report -> {OUTPUT_MD}")


if __name__ == "__main__":
    main()
