"""Execute the required SQL queries against books.db and record their output.

Collectively the queries cover every clause the brief asks for:
SELECT/WHERE, ORDER BY, LIMIT, DISTINCT, IN, BETWEEN, and a JOIN across the
two tables. Each query string and its result table are written to
queries_output.md so the output is reviewable without re-running anything.

Executed with the sqlite3 module directly (no pandas) -- the pandas equivalents
are demonstrated separately in pandas_check.py.
"""

import sqlite3

DB_PATH = "books.db"
OUTPUT_MD = "queries_output.md"

# The join query is defined separately because pandas_check.py reproduces this
# exact result with pd.merge, so both files must stay in step.
JOIN_QUERY = """
SELECT b.title, c.category_name, b.rating, b.price_gbp, b.price_inr
FROM books b
JOIN categories c ON b.category_id = c.category_id
WHERE b.rating >= 4
ORDER BY c.category_name ASC, b.rating DESC, b.title ASC
LIMIT 10
"""

QUERIES = [
    (
        "Q1 - SELECT / WHERE",
        "Titles and prices of every book rated 4 stars or better.",
        """
SELECT title, rating, price_gbp
FROM books
WHERE rating >= 4
""",
    ),
    (
        "Q2 - ORDER BY + LIMIT",
        "The 10 most expensive books in the catalogue.",
        """
SELECT title, price_gbp, price_inr
FROM books
ORDER BY price_gbp DESC
LIMIT 10
""",
    ),
    (
        "Q3 - DISTINCT",
        "The distinct star ratings actually present in the scraped data.",
        """
SELECT DISTINCT rating
FROM books
ORDER BY rating DESC
""",
    ),
    (
        "Q4 - BETWEEN",
        "Books priced between GBP 20.00 and GBP 30.00 inclusive.",
        """
SELECT title, price_gbp
FROM books
WHERE price_gbp BETWEEN 20.00 AND 30.00
ORDER BY price_gbp ASC
""",
    ),
    (
        "Q5 - IN",
        "Books belonging to the Travel or Philosophy categories.",
        """
SELECT b.title, c.category_name
FROM books b
JOIN categories c ON b.category_id = c.category_id
WHERE c.category_name IN ('Travel', 'Philosophy')
ORDER BY c.category_name, b.title
""",
    ),
    (
        "Q6 - JOIN (books x categories)",
        "The 10 highest-rated books with their category name, joined across "
        "the two tables on the category_id foreign key.",
        JOIN_QUERY,
    ),
]

# Lookup so pandas_check.py reads back the exact strings executed here, rather
# than keeping its own copies that could drift out of step.
QUERIES_BY_NAME = {name: sql for name, _, sql in QUERIES}


def markdown_table(columns, rows):
    """Render a result set as a GitHub-flavoured Markdown table."""
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = [
        "| " + " | ".join(str(value).replace("|", "\\|") for value in row) + " |"
        for row in rows
    ]
    return "\n".join([header, divider, *body])


def main():
    connection = sqlite3.connect(DB_PATH)
    sections = [
        "# SQL query results\n",
        f"Generated by `run_queries.py` against `{DB_PATH}`.\n",
    ]

    for name, description, sql in QUERIES:
        cursor = connection.execute(sql)
        columns = [column[0] for column in cursor.description]
        rows = cursor.fetchall()

        print(f"{name}: {len(rows)} rows")

        sections.append(f"## {name}\n")
        sections.append(f"{description}\n")
        sections.append(f"```sql{sql}```\n")
        sections.append(f"**{len(rows)} row(s) returned**\n")
        sections.append(markdown_table(columns, rows) + "\n")

    connection.close()

    with open(OUTPUT_MD, "w", encoding="utf-8") as handle:
        handle.write("\n".join(sections))

    print(f"\nWrote {len(QUERIES)} queries and their output -> {OUTPUT_MD}")


if __name__ == "__main__":
    main()
